# Defaults
ARG REDIS_VERSION=7.0.5-alpine3.16

FROM redis:${REDIS_VERSION}

LABEL com.iotportaldevicemanagement.product="iotportaldevicemanagement"

COPY --chown=redis:redis configs/redis.conf /usr/local/etc/redis/redis.conf

USER redis:redis

CMD ["redis-server", "/usr/local/etc/redis/redis.conf"]

# docker build -f Dockerfile.production -t iotportaldevicemanagement-redis .